// Extracts the game icons the app uses from @iconify-json/game-icons into a small generated
// module, so the bundle only ships what it needs and works offline.
// Icons by the game-icons.net authors (https://game-icons.net), licensed CC BY 3.0.
// Usage: npm run icons (after editing the list below).
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const set = JSON.parse(readFileSync(require.resolve("@iconify-json/game-icons/icons.json"), "utf8"));

/** App name -> game-icons name. */
const ICONS = {
  // races
  humans: "farmer",
  elves: "woman-elf-face",
  dwarves: "dwarf-face",
  orcs: "orc-head",
  giants: "giant",
  wizards: "wizard-face",
  ratmen: "rat",
  tritons: "triton-head",
  trolls: "troll",
  skeletons: "skeleton",
  halflings: "hobbit-dwelling",
  amazons: "bow-arrow",
  // powers
  alchemist: "cauldron",
  merchant: "two-coins",
  fortified: "stone-tower",
  forest: "pine-tree",
  hill: "hills",
  swamp: "swamp",
  mounted: "horse-head",
  commando: "knife-thrust",
  seafaring: "sailboat",
  flying: "feathered-wing",
  wealthy: "diamonds",
  pillaging: "fire",
  underworld: "cave-entrance",
  stout: "strong",
  peaceful: "peace-dove",
  // map
  farmland: "wheat",
  mountain: "mountains",
  sea: "waves",
  lake: "water-drop",
  mine: "mining",
  cave: "cave-entrance",
  magic: "magic-swirl",
  lostTribe: "hut",
  fortress: "stone-tower",
  lair: "stone-pile",
  hole: "hobbit-door",
  // interface
  coins: "two-coins",
  hand: "hand",
  tokens: "swordman",
  dice: "perspective-dice-six-faces-random",
  decline: "sleepy",
  trophy: "trophy-cup",
  crown: "crown",
  podium: "podium",
  swords: "crossed-swords",
  shield: "round-shield",
  hourglass: "hourglass",
  speaker: "speaker",
  speakerOff: "speaker-off",
  map: "treasure-map",
  scroll: "scroll-unfurled",
  info: "info",
  settings: "cog",
  exit: "exit-door",
  save: "save",
  chart: "histogram",
  stopwatch: "stopwatch",
  person: "person",
  brokenShield: "broken-shield",
  laurels: "laurels",
  target: "targeting",
  expand: "expand",
  contract: "contract",
  chat: "talk",
  log: "quill-ink",
  market: "card-pick",
};

const missing = Object.entries(ICONS).filter(([, name]) => !set.icons[name]);
if (missing.length) throw new Error(`Unknown game-icons: ${missing.map(([, n]) => n).join(", ")}`);

const entries = Object.entries(ICONS).map(([key, name]) => `  ${JSON.stringify(key)}: ${JSON.stringify(set.icons[name].body)},`);
const out = `// Generated by scripts/build-icons.mjs — do not edit by hand.
// Icons from game-icons.net (https://game-icons.net), CC BY 3.0. Each value is the inner SVG of a ${set.width}x${set.height} icon.
export const ICON_BODIES = {
${entries.join("\n")}
} as const;

export type IconName = keyof typeof ICON_BODIES;
export const ICON_VIEWBOX = "0 0 ${set.width} ${set.height}";
`;
writeFileSync(new URL("../src/ui/icons/generated.ts", import.meta.url), out);
console.log(`Wrote ${entries.length} icons.`);
